### PR TITLE
Repair creative item classification

### PR DESCRIPTION
**Pull request by lt-name**
Repair item classification
Repair method found from powernukkit
(Google Translate)

### CODE REVIEW

**Comment by PetteriM1** [comment]
You should create this as a separate creative items list for 1.16.100+ only. Also if possible please keep the customizations.

**Comment by lt-name** [comment]
> You should create this as a separate creative items list for 1.16.100+ only. Also if possible please keep the customizations.

Is it 409 or 419?
Sorry for my bad English, what do you mean by "customizations"?
(Google Translate)

**Comment by PetteriM1** [comment]
> > You should create this as a separate creative items list for 1.16.100+ only. Also if possible please keep the customizations.
> 
> Is it 409 or 419?
> Sorry for my bad English, what do you mean by "customizations"?
> (Google Translate)

409+ is ok and by customizations I mean the few blocks/items I have there that vanilla creative inventory doesn't have

**Comment by lt-name** [comment]
> > > You should create this as a separate creative items list for 1.16.100+ only. Also if possible please keep the customizations.
> > 
> > 
> > Is it 409 or 419?
> > Sorry for my bad English, what do you mean by "customizations"?
> > (Google Translate)
> 
> 409+ is ok and by customizations I mean the few blocks/items I have there that vanilla creative inventory doesn't have

For example: 11?

**Comment by lt-name** [comment]
I copied nkx's creativeitems.json

**Comment by PetteriM1** [comment]
> I copied nkx's creativeitems.json

The reason we don't use the full creative items list from NukkitX is that we don't want all the unsupported blocks to be on the list

**Comment by lt-name** [comment]
I conducted some tests, the order of CreativeItemList does affect the client, I think creativeitems407.json needs to be reordered (Google Translate)

**Pull request closed without merging**
