### PR TITLE
Use UUID for player data saving

### PR DESCRIPTION
**Pull request by PetteriM1**
Using UUID for player data saving like NukkitX does.
Old data will be converted automatically.

Dev builds: https://app.circleci.com/pipelines/github/PetteriM1/NukkitPetteriM1Edition?branch=uuid
(As always, remember to take a backup before using any experimental builds)

### CODE REVIEW

**Comment by TanToan99** [comment]
sometime login and crash client with invalid data :(

**Comment by PetteriM1** [comment]
> sometime login and crash client with invalid data :(

Invalid data? Can you send the player data file for me so I can investigate this? Also is the data created in NukkitX or converted from the old format or was the player not played on the server before that?

**Comment by TanToan99** [comment]
image
image

server no data player file create, It happens when a new player join the server

**Comment by TanToan99** [comment]
I builded 6ec61b6 version, but it continute invalid data ...

**Comment by tuilakhanh** [comment]
It's only happen when using uuid brand with custom nemisys proxy

**Comment by PetteriM1** [comment]
> It's only happen when using uuid brand with custom nemisys proxy

This branch is not supported by SynapseAPI yet but I can make a synapse build for it

**Comment by tuilakhanh** [comment]
> > It's only happen when using uuid brand with custom nemisys proxy
> 
> This branch is not supported by SynapseAPI yet but I can make a synapse build for it

I try fixing synapseapi and it work ^.^ Thank you bro

**Pull request merged**
